[tool.poetry]
name = "docker_python_poetry"
version = "0.0.3"
description = "Docker images python+poetry applications"
authors = ["Mykola <nchernov@gmail.com>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"