name: Build and Deploy

on:
  push:
    tags:
      - "v*.*.*"

env:
  DOCKER_LOGIN: simple2b
  IMAGE: simple2b/dockerizer-python-poetry
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    name: Build and Push
    runs-on: Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker meta for python-vpn
        id: meta_vpn_python
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.IMAGE }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_LOGIN }}
          password: ${{ env.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta_vpn_python.outputs.tags }}
          labels: ${{ steps.meta_vpn_python.outputs.labels }}
